/* 
 * Copyright (C) 2016 Johannes Wilke
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.freebooth.photobooth;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.util.prefs.Preferences;
import javax.swing.BorderFactory;

/**
 *
 * @author johannes
 */
public class PrintDialog extends javax.swing.JDialog {



    Process proc;
    boolean result;
    Preferences prefs;
    Preferences onlinePrefs;
    PhotoboothFrame pf;

    public PrintDialog() {
    }
    
    /**
     * Creates new form SaveDialog
     *
     * @param parent
     * @param modal
     */
    public PrintDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        prefs = Preferences.userNodeForPackage(PhotoboothFrame.class);
        onlinePrefs = Preferences.userNodeForPackage(ShareOptionsPanel.class);
        getContentPane().setBackground(Color.decode(prefs.get("background_color", "#333333")));
        setUndecorated(true);
        getRootPane().setBorder(BorderFactory.createLineBorder(Color.decode(prefs.get("button_color", "#ED5E2F"))));
        
        initComponents();
        List<javax.swing.JButton> buttonList = new ArrayList<>();
        buttonList.add(jButton3);
        buttonList.add(jButton5);
        
        for(javax.swing.JButton button : buttonList){
            button.setOpaque(true);
            button.setBackground(Color.decode(prefs.get("button_color", "#ED5E2F")));
            button.setForeground(Color.decode(prefs.get("button_foreground", "#ffffff")));
            Font font = button.getFont();
            button.setFont(new Font(font.getName(),font.getStyle(),prefs.getInt("button_font_size", 20)));
        }
        
        jLabel3.setForeground(Color.decode(prefs.get("text_color", "#ffffff")));
        pack();
        setLocationRelativeTo(parent);



        
        //System.out.println(this.imageName);
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("properties/Bundle"); // NOI18N
        setTitle(bundle.getString("PrintDialog.title_1")); // NOI18N
        setAlwaysOnTop(true);
        setBackground(java.awt.Color.gray);
        setForeground(java.awt.Color.white);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(600, 300));
        setModal(true);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 10, 0};
        layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0};
        getContentPane().setLayout(layout);

        jButton3.setBackground(new java.awt.Color(64, 64, 64));
        jButton3.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jButton3.setForeground(java.awt.Color.white);
        jButton3.setText(bundle.getString("PrintDialog.jButton3.text_1")); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setOpaque(true);
        jButton3.setPreferredSize(new java.awt.Dimension(160, 32));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jButton3, gridBagConstraints);

        jButton5.setBackground(new java.awt.Color(50, 50, 50));
        jButton5.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jButton5.setForeground(java.awt.Color.white);
        jButton5.setText(bundle.getString("PrintDialog.jButton5.text_1")); // NOI18N
        jButton5.setToolTipText(bundle.getString("PrintDialog.jButton5.toolTipText_1")); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusPainted(false);
        jButton5.setMaximumSize(new java.awt.Dimension(0, 0));
        jButton5.setOpaque(true);
        jButton5.setPreferredSize(new java.awt.Dimension(160, 28));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jButton5, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel3.setText(bundle.getString("PrintDialog.jLabel3.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(jLabel3, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        this.result = true;
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        result = false;
        this.dispose();

    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
